export const CONTRACT_DEPLOY_SUBMITTED = 'CONTRACT_DEPLOY_SUBMITTED';
export const CONTRACT_DEPLOY_COMPLETE = 'CONTRACT_DEPLOY_COMPLETE';
export const CONTRACT_DEPLOY_REJECTED = 'CONTRACT_DEPLOY_REJECTED';

export const TRANSACTION_SUBMITTED = 'TRANSACTION_SUBMITTED';
export const TRANSACTION_COMPLETE = 'TRANSACTION_COMPLETE';
export const TRANSACTION_REJECTED = 'TRANSACTION_REJECTED';
