// * Set Actions
export const PROVIDER_SET = "PROVIDER_SET";
export const PROVIDER_SET_MULTIPLE = "PROVIDER_SET_MULTIPLE";
export const PROVIDER_SET_STATUS = "PROVIDER_SET_STATUS";

export const ENABLE_REQUEST = "ENABLE_REQUEST";
export const ENABLE_SUCCESS = "ENABLE_SUCCESS";
export const ENABLE_FAILURE = "ENABLE_FAILURE";

export const INIT_CONTRACT_REQUEST = "INIT_CONTRACT_REQUEST";
export const INIT_CONTRACT_SUCCESS = "INIT_CONTRACT_SUCCESS";
export const INIT_CONTRACT_FAILURE = "INIT_CONTRACT_FAILURE";

export const BALANCE_SET = "BALANCE_SET";
export const ENS_ADDRESS_SET = "ENS_ADDRESS_SET";
export const SET_NETWORK = "SET_NETWORK";
export const NONCE_SET = "NONCE_SET";

/* ----------------------- */
/*         Contact         */
/* ----------------------- */
export const CONTRACT_INITIALIZE_REQUEST = "CONTRACT_INITIALIZE_REQUEST";
export const CONTRACT_INITIALIZE_SUCCESS = "CONTRACT_INITIALIZE_SUCCESS";
export const CONTRACT_INITIALIZE_FAILURE = "CONTRACT_INITIALIZE_FAILURE";

export const CONTRACT_DEPLOY_REQUEST = "CONTRACT_DEPLOY_REQUEST";
export const CONTRACT_DEPLOY_SUCCESS = "CONTRACT_DEPLOY_SUCCESS";
export const CONTRACT_DEPLOY_FAILURE = "CONTRACT_DEPLOY_FAILURE";

export const CONTRACT_DEPLOY_FROM_BYTECODE_REQUEST =
  "CONTRACT_DEPLOY_FROM_BYTECODE_REQUEST";
export const CONTRACT_DEPLOY_FROM_BYTECODE_SUCCESS =
  "CONTRACT_DEPLOY_FROM_BYTECODE_SUCCESS";
export const CONTRACT_DEPLOY_FROM_BYTECODE_FAILURE =
  "CONTRACT_DEPLOY_FROM_BYTECODE_FAILURE";

/* ----------------------- */
/*         Wallet         */
/* ----------------------- */

export const SIGNER_GET_REQUEST = "SIGNER_GET_REQUEST";
export const SIGNER_GET_SUCCESS = "SIGNER_GET_SUCCESS";
export const SIGNER_GET_FAILURE = "SIGNER_GET_FAILURE";

export const WALLET_PROVIDER_GET_REQUEST = "WALLET_PROVIDER_GET_REQUEST";
export const WALLET_PROVIDER_GET_SUCCESS = "WALLET_PROVIDER_GET_SUCCESS";
export const WALLET_PROVIDER_GET_FAILURE = "WALLET_PROVIDER_GET_FAILURE";

export const WALLET_SIGN_TYPED_MESSAGE_REQUEST =
  "WALLET_SIGN_TYPED_MESSAGE_REQUEST";
export const WALLET_SIGN_TYPED_MESSAGE_SUCCESS =
  "WALLET_SIGN_TYPED_MESSAGE_SUCCESS";
export const WALLET_SIGN_TYPED_MESSAGE_FAILURE =
  "WALLET_SIGN_TYPED_MESSAGE_FAILURE";
export const WALLET_SIGN_MESSAGE_REQUEST = "SIGN_MESSAGE";
export const WALLET_SIGN_MESSAGE_SUCCESS = "WALLET_SIGN_MESSAGE_SUCCESS";
export const WALLET_SIGN_MESSAGE_FAILURE = "WALLET_SIGN_MESSAGE_FAILURE";

export const WALLET_SIGN_TRANSACTION_REQUEST =
  "WALLET_SIGN_TRANSACTION_REQUEST";
export const WALLET_SIGN_TRANSACTION_SUCCESS =
  "WALLET_SIGN_TRANSACTION_SUCCESS";
export const WALLET_SIGN_TRANSACTION_FAILURE =
  "WALLET_SIGN_TRANSACTION_FAILURE";

export const WALLET_SEND_TRANSACTION_REQUEST =
  "WALLET_SEND_TRANSACTION_REQUEST";
export const WALLET_SEND_TRANSACTION_SUCCESS =
  "WALLET_SEND_TRANSACTION_SUCCESS";
export const WALLET_SEND_TRANSACTION_FAILURE =
  "WALLET_SEND_TRANSACTION_FAILURE";

export const SET_WALLET = "SET_WALLET";
export const SET_WALLET_REQUEST = "SET_WALLET_REQUEST";
export const SET_WALLET_SUCCESS = "SET_WALLET_SUCCESS";
export const SET_WALLET_FAILURE = "SET_WALLET_FAILURE";
export const SET_ADDRESS = "SET_ADDRESS";

export const TRANSACTION_MONITOR_REQUEST = "TRANSACTION_MONITOR_REQUEST";
export const TRANSACTION_MONITOR_SUCCESS = "TRANSACTION_MONITOR_SUCCESS";
export const TRANSACTION_MONITOR_FAILURE = "TRANSACTION_MONITOR_FAILURE";

export const CONTRACT_DEPLOY_MONITOR_REQUEST =
  "CONTRACT_DEPLOY_MONITOR_REQUEST";
export const CONTRACT_DEPLOY_MONITOR_SUCCESS =
  "CONTRACT_DEPLOY_MONITOR_SUCCESS";
export const CONTRACT_DEPLOY_MONITOR_FAILURE =
  "CONTRACT_DEPLOY_MONITOR_FAILURE";
