// * Set Actions
export const SET_PROVIDER = "SET_PROVIDER";
export const PROVIDER_SELECT_REQUEST = "PROVIDER_SELECT_REQUEST";
export const PROVIDER_SELECT_SUCCESS = "PROVIDER_SELECT_SUCCESS";
export const PROVIDER_SELECT_FAILURE = "PROVIDER_SELECT_FAILURE";
